.Net/ASP.NET_Core/MVC/N-Tier_Architecture/SimpleBlog/SimpleBlog/Controllers/BlogPostController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SimpleBlog.DataAccess.Repository.IRepository;
using SimpleBlog.Models.Models;
using SimpleBlog.Models.ViewModels;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace SimpleBlog.Web.Controllers
{
    
    public class BlogPostController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        private readonly UserManager<ApplicationUser> _userManager;
        public BlogPostController(IUnitOfWork unitOfWork, UserManager<ApplicationUser> userManager)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;

        }
        public IActionResult Index()
        {
            List<BlogPost> blogPostList = _unitOfWork.BlogPost.GetAll(includeProperties: "Author,Comments").ToList();

            return View(blogPostList);
        }
    
        public IActionResult Upsert(int? id)
        {
           

            if (id == null || id == 0)
            {
                BlogPost newPost = new();
                // create
                return View(newPost);
            }
            else
            {
                // update
                BlogPost post = _unitOfWork.BlogPost.Get(u => u.Id == id, includeProperties: "Author");
                return View(post);
            }

        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Upsert(BlogPost obj)
        {
            if (ModelState.IsValid)
            {
                if (obj.Id == 0)
                {
                    obj.DateCreated = DateTime.Now;
                    var currentUser = await _userManager.GetUserAsync(User);
                    obj.Author = currentUser;
                    _unitOfWork.BlogPost.Add(obj);
                    TempData["success"] = "Blog Post created successfully.";
                }
                else
                {
                    _unitOfWork.BlogPost.Update(obj);
                    TempData["success"] = "Blog Post updated successfully.";
                }

                _unitOfWork.Save();

                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult Detail(int? id)
        {

            BlogPost post = _unitOfWork.BlogPost.Get(u => u.Id == id, includeProperties:"Author,Comments");
            DetailVM detailVM = new()
            {
                BlogPost = post,
                NewComment = new Comment() 
            };
            return View(detailVM);
        }

        public IActionResult UserPosts(string id)
        {
            List<BlogPost> blogPostList = _unitOfWork.BlogPost.GetAll(x => x.AuthorId == id, includeProperties: "Author,Comments").ToList();
            ApplicationUser user = _userManager.FindByIdAsync(id).Result;

            UserBlogPostsViewModel viewModel;

            if (blogPostList.Count == 0)
            {
                viewModel = new UserBlogPostsViewModel
                {
                    BlogPosts = new List<BlogPost>(),
                    User = user
                };
            }
            else
            {
                viewModel = new UserBlogPostsViewModel
                {
                    BlogPosts = blogPostList,
                    User = user
                };
            }

            return View(viewModel);
        }


        #region API

        [Authorize]
        public IActionResult Delete(int? id)
        {
            var postToBeDeleted = _unitOfWork.BlogPost.Get(u => u.Id == id);
            if (postToBeDeleted == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }
            _unitOfWork.BlogPost.Remove(postToBeDeleted);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Blog post deleted successfully." });
        }

        #endregion
    }
}

.Net/ASP.NET_Core/MVC/N-Tier_Architecture/SimpleBlog/SimpleBlog/Views/BlogPost/Detail.cshtml
@model DetailVM
@{
    ViewData["Title"] = $"Detail of {Model.BlogPost.Title}";
}

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-4">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2 "> @(Model.BlogPost.Title)</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <div class="row pb-4">

            <div class="col-12 ">
                <p>@Html.Raw(Model.BlogPost.Content)</p>
            </div>
            <span class="text-end col-12">@Model.BlogPost.DateCreated.ToString("MMMM d, yyyy")</span>
            <a class="text-end col-12" asp-controller="BlogPost" asp-action="UserPosts" asp-route-id="@Model.BlogPost.Author.Id">
                @Model.BlogPost.Author.Name
            </a>
        </div>
        <div class="row pb-4">
            @if (SignInManager.IsSignedIn(User))
            {

                <div class="col-4">
                    <a asp-controller="BlogPost" asp-action="Upsert" asp-route-Id="@Model.BlogPost.Id" class="btn btn-primary border form-control">
                        Edit
                    </a>
                </div>
                <div class="col-4">
                    <a id="deleteButtonBlogPost" asp-controller="BlogPost" asp-action="Delete" asp-route-id="@Model.BlogPost.Id"
                       class="btn btn-danger border form-control">
                        Delete
                    </a>
                </div>

            }
            else
            {
                <div class="col-8"> </div>

            }
            <div class="col-4 text-end">
                <a asp-controller="Home" asp-action="Index" class="btn btn-outline-primary border form-control">
                    Back to List
                </a>
            </div>

        </div>
        <div class="row pb-4">
            <div class="col-12">
                <h4>Add a Comment</h4>
                <form asp-controller="Comment" asp-action="Create" class="row" method="post" asp-model="@Model">
                    <input type="hidden" asp-for="@Model.NewComment.BlogPostId" value="@Model.BlogPost.Id" />

                    <div class="form-floating py-2 col-12 ">
                        <input id="commentAuthor" class="form-control border-0 shadow" asp-for="@Model.NewComment.CommentAuthor" />
                        <label class="ms-2" asp-for="@Model.NewComment.CommentAuthor">Name</label>
                        <span asp-validation-for="@Model.NewComment.CommentAuthor" class="text-danger"></span>
                    </div>

                    <div class="form-group col-12 ">
                        <label asp-for="@Model.NewComment.Text" class="ms-2 text-muted">Comment</label>
                        <textarea class="form-control border-0 shadow" asp-for="@Model.NewComment.Text" rows="3"></textarea>
                        <span asp-validation-for="@Model.NewComment.Text" class="text-danger"></span>
                    </div>

                    <div class="col-12 text-end">
                        <button type="submit" class="btn btn-primary mt-3" asp-controller="Comment" asp-action="Create">Submit</button>
                    </div>
                </form>
            </div>
        </div>

        @if (Model.BlogPost.Comments.Count != 0)
        {
            <div class="row pb-3">
                <div class="col-12">
                    <h4>Comments</h4>

                    @foreach (var comment in Model.BlogPost.Comments)
                    {
                        <div class="card mb-3">
                            <div class="card-header">
                                <h6 class="card-title my-2"><b>@comment.CommentAuthor</b></h6>
                            </div>
                            <div class="card-body">
                                <p class="card-text">@comment.Text</p>
                            </div>
                            <div class="card-footer">
                                <div class="row justify-content-between align-items-center">
                                    <div class="col text-end">
                                        <small>@comment.DatePosted.ToString("MMMM d, yyyy")</small>
                                    </div>
                                    @if (SignInManager.IsSignedIn(User))
                                    {
                                        <div class="col-auto">
                                            <a class="deleteButtonComment btn btn-sm btn-outline-danger"
                                               data-url="@Url.Action("Delete", "Comment", new { id = comment.Id })"
                                               data-current-url="@Context.Request.Path">
                                                <i class="bi bi-trash"></i> Delete
                                            </a>
                                        </div>
                                    }

                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        }

       


    </div>

</div>


@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
    <script src="~/js/blogPostDelete.js"></script>
    <script src="~/js/commentDelete.js"></script>
            }

.Net/ASP.NET_Core/MVC/N-Tier_Architecture/SimpleBlog/SimpleBlog/Views/BlogPost/Index.cshtml
@model List<BlogPost>
@{
    ViewData["Title"] = "All Blog Posts";
}
<div class="card border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-4">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="py-2 text-white">Blog Posts</h2>
            </div>
        </div>
    </div>
    <div class="card-body py-4">
        <div class="row pb-3">
            <div class="col-6">
            </div>
            <div class="col-6 text-end">
                <a asp-controller="BlogPost" asp-action="Upsert" class="btn btn-primary"><i class="bi bi-plus-lg"></i> Create New Blog Post</a>
            </div>
        </div>

        @if (Model.Count == 0)
        {
            <div class="alert alert-info">
                <p><strong>Oops! No blog posts available.</strong></p>
                <p>Looks like there are no blog posts at the moment.</p>
            </div>
        }
        else
        {
            @foreach (var post in Model)
            {
                <div class="card shadow border-0 mb-5">
                    <div class="card-header bg-primary ml-0">
                        <div class="row">

                            <div class="col-6">
                                <h2 class="py-2 m-0 text-white">@post.Title</h2>
                            </div>
                            <div class="col-6 d-flex align-items-center justify-content-end">
                                <a asp-controller="BlogPost" asp-action="Detail" asp-route-Id="@post.Id" class="btn btn-primary"><i class="bi bi-info-circle"></i> Detail</a>
                            </div>

                        </div>
                    </div>
                    <div class="card-body pt-4 pb-0">
                        <div class="row mb-2">
                            <div class="col-12 ">
                                <p>@Html.Raw(post.Content)</p>
                            </div>
                            <span class="text-end col-12">@post.DateCreated.ToString("MMMM d, yyyy")</span>
                            <a class="text-end col-12" asp-controller="BlogPost" asp-action="UserPosts" asp-route-id="@post.Author.Id">
                                @post.Author.Name
                            </a>

                        </div>

                        @if (post.Comments.Count == 0)
                        {
                            <div class="row mb-2">
                                <span><i class="bi bi-chat-right-text"></i>  @post.Comments.Count()</span>
                            </div>
                        }
                        else
                        {
                            <div class="accordion accordion-flush" id="accordion-@post.Id">
                                <div class="accordion-item">
                                    <h2 class="accordion-header ">
                                        <button class="accordion-button custom-accordion-button collapsed px-0" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-@post.Id" aria-expanded="false" aria-controls="collapse-@post.Id">
                                            <span><i class="bi bi-chat-right-text"></i>  @post.Comments.Count()</span>
                                        </button>
                                    </h2>
                                    <div id="collapse-@post.Id" class="accordion-collapse collapse" data-bs-parent="#accordion-@post.Id">
                                        <div class="accordion-body">
                                            <div class="row">
                                                <div class="col-12">
                                                    <h4>Comments</h4>

                                                    @foreach (var comment in post.Comments)
                                                    {
                                                        <div class="card mb-3">
                                                            <div class="card-header">
                                                                <h6 class="card-title my-2"><b>@comment.CommentAuthor</b></h6>
                                                            </div>
                                                            <div class="card-body">
                                                                <p class="card-text">@comment.Text</p>
                                                            </div>
                                                            <div class="card-footer">
                                                                <div class="row justify-content-between align-items-center">
                                                                    <div class="col text-end">
                                                                        <small>@comment.DatePosted.ToString("MMMM d, yyyy")</small>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    }
                                                </div>
                                            </div>

                                        </div>
                                    </div>

                                </div>
                            </div>
                        }

                    </div>

                </div>


            }
        }

    </div>
</div>

.Net/ASP.NET_Core/MVC/N-Tier_Architecture/SimpleBlog/SimpleBlog/Views/BlogPost/Upsert.cshtml
@model BlogPost
@{
    if (Model.Id == 0)
    {
        ViewData["Title"] = "Create";
    }
    else
    {
        ViewData["Title"] = "Edit";
    }
}

<div class="card shadow border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-4">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2 "> @(Model.Id != 0 ? "Update" : "Create") Blog Post</h2>
            </div>
        </div>
    </div>
    <div class="card-body p-4">
        <form id="blogPostForm" method="post" class="row" enctype="multipart/form-data">
            <input asp-for="Id" hidden />

            <div class="col-12">
                <div class="p-3">
                    <div class="form-floating py-2 col-12">
                        <input asp-for="Title" id="Title" class="form-control border-0 shadow" />
                        <label asp-for="Title" class="ms-2"></label>
                        <span id="validationMessageTitle" class="text-danger"></span>
                    </div>

                    <div class="py-2 col-12">
                        <label asp-for="Content" class="ms-3 text-muted"></label>
                        <textarea id="tinyEditor" asp-for="Content" class="form-control border-0 shadow"></textarea>
                        <span id="validationMessageContent" class="text-danger"></span>
                    </div>


                    @if (Model.Id != 0)
                    {
                        <div class="form-floating py-2 col-12">
                            <input value="@Model.DateCreated.ToString("MMMM d, yyyy")" class="form-control border-0 shadow" disabled />
                            <label asp-for="DateCreated" class="ms-2"></label>

                        </div>
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Author.Name" class="form-control border-0 shadow" disabled />
                            <label asp-for="Author.Name" class="ms-2"></label>
                        </div>

                    }
                </div>

            </div>
            <div class="row pt-2">
                <div class="col-6 col-md-3">
                    @if (Model.Id != 0)
                    {
                        <button type="submit" id="submit" class="btn btn-primary form-control">Update</button>
                    }
                    else
                    {
                        <button type="submit" id="submit" class="btn btn-primary form-control">Create</button>
                    }

                </div>
                <div class="col-6 col-md-3">
                    <a asp-controller="BlogPost" asp-action="Index" class="btn btn-outline-primary border form-control">
                        Back to List
                    </a>
                </div>
            </div>

        </form>
    </div>
</div>


@section Scripts{
    <script src="~/js/blogPostFormValidation.js"></script>
}

.Net/ASP.NET_Core/MVC/N-Tier_Architecture/SimpleBlog/SimpleBlog/Views/BlogPost/UserPosts.cshtml
@model UserBlogPostsViewModel
@{
    var userId = Model.User.Id;
    var user = await _userManager.FindByIdAsync(userId);

    ViewData["Title"] = $"{user.Name}'s Blog Posts";
}

<div class="card border-0 mt-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-4">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="py-2 text-white">@user.Name's Blog Posts</h2>
            </div>
        </div>
    </div>
    <div class="card-body py-4">
        <div class="row pb-3">
            <div class="col-6">
            </div>
            @if (SignInManager.IsSignedIn(User))
            {
                <div class="col-6 text-end">
                    <a asp-controller="BlogPost" asp-action="Upsert" class="btn btn-primary"><i class="bi bi-plus-lg"></i> Create New Blog Post</a>
                </div>
            }
        </div>

        @if (Model.BlogPosts.Count == 0)
        {
            <div class="alert alert-info">
                <p><strong>No blog posts available.</strong></p>
                <p>Looks like there are no blog posts at the moment.</p>
            </div>
        }
        else
        {
            @foreach (var post in Model.BlogPosts)
            {
                <div class="card shadow border-0 mb-5">
                    <div class="card-header bg-primary ml-0">
                        <div class="row">
                            <div class="col-6">
                                <h2 class="py-2 m-0 text-white">@post.Title</h2>
                            </div>
                            <div class="col-6 d-flex align-items-center justify-content-end">
                                <a asp-controller="BlogPost" asp-action="Detail" asp-route-Id="@post.Id" class="btn btn-primary"><i class="bi bi-info-circle"></i> Detail</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body pt-4 pb-0">
                        <div class="row mb-2">
                            <div class="col-12">
                                <p>@Html.Raw(post.Content)</p>
                            </div>
                            <span class="text-end col-12">@post.DateCreated.ToString("MMMM d, yyyy")</span>
                            <a class="text-end col-12" asp-controller="BlogPost" asp-action="UserPosts" asp-route-id="@post.Author.Id">
                                @post.Author.Name
                            </a>
                        </div>

                        @if (post.Comments.Count == 0)
                        {
                            <div class="row mb-2">
                                <span><i class="bi bi-chat-right-text"></i>  @post.Comments.Count()</span>
                            </div>
                        }
                        else
                        {
                            <div class="accordion accordion-flush" id="accordion-@post.Id">
                                <div class="accordion-item">
                                    <h2 class="accordion-header ">
                                        <button class="accordion-button custom-accordion-button collapsed px-0" type="button" data-bs-toggle="collapse" data-bs-target="#collapse-@post.Id" aria-expanded="false" aria-controls="collapse-@post.Id">
                                            <span><i class="bi bi-chat-right-text"></i>  @post.Comments.Count()</span>
                                        </button>
                                    </h2>
                                    <div id="collapse-@post.Id" class="accordion-collapse collapse" data-bs-parent="#accordion-@post.Id">
                                        <div class="accordion-body">
                                            <div class="row">
                                                <div class="col-12">
                                                    <h4>Comments</h4>

                                                    @foreach (var comment in post.Comments)
                                                    {
                                                        <div class="card mb-3">
                                                            <div class="card-header">
                                                                <h6 class="card-title my-2"><b>@comment.CommentAuthor</b></h6>
                                                            </div>
                                                            <div class="card-body">
                                                                <p class="card-text">@comment.Text</p>
                                                            </div>
                                                            <div class="card-footer">
                                                                <div class="row justify-content-between align-items-center">
                                                                    <div class="col text-end">
                                                                        <small>@comment.DatePosted.ToString("MMMM d, yyyy")</small>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    }
                                                </div>
                                            </div>

                                        </div>
                                    </div>

                                </div>
                            </div>
                        }
                    </div>
                </div>
            }
        }
    </div>
</div>